# Book settings
title: ""
author: "이현열"
logo: logo.png

repository:
  url: https://github.com/hyunyulhenry/quant_python
  branch: master

collapse_inactive_chapters: true
collapse_inactive_sections: true

use_thebelab_button: false

parse:
  myst_extended_syntax: true
  
execute:
  execute_notebooks: 'off'

html:
  comments:
    hypothesis: true
    utterances:
      repo: "hyunyulhenry/quant_python"
  
latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    show_authors: false
    html_show_copyright: false

bibtex_bibfiles:
   - references.bib

scholar:
  style: apa

